--
-- Data for Name: email_templates; Type: TABLE DATA; Schema: public; Owner: postgres
--
INSERT INTO
    "public"."email_templates" (
        "template_key",
        "subject_translations",
        "body_html_translations",
        "description_translations",
        "available_placeholders",
        "created_at",
        "updated_at"
    )
VALUES
    (
        'admin_invitation',
        '{"ar": "دعوة للانضمام كمسؤول في منصة Eventy360", "en": "Invitation to Join as an Administrator on Eventy360", "fr": "Invitation à rejoindre en tant qu''administrateur sur Eventy360"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>يسرنا دعوتكم للانضمام إلى فريق إدارة منصة Eventy360 بصفة مسؤول. هذه الدعوة تعكس ثقتنا في خبراتكم ومؤهلاتكم للمساهمة في تطوير وإدارة المنصة.</p><p>يرجى النقر على الرابط أدناه لإكمال عملية تسجيل حسابكم كمسؤول:</p><p><a href=\"[signin_link]\">قبول الدعوة</a></p><p>يرجى العلم بأن هذا الرابط صالح لمدة [validity_period] من تاريخ استلام هذه الرسالة.</p><p>ملاحظة هامة: إذا لم تكونوا تتوقعون استلام هذه الدعوة، أو إذا كان هناك أي استفسارات، يرجى التواصل معنا مباشرة على [platform_management_email]، وعدم اتخاذ أي إجراء بخصوص هذه الرسالة.</p><p>نتطلع إلى انضمامكم إلى فريقنا والعمل سوياً لتحقيق أهداف المنصة.</p><p>مع خالص التقدير والاحترام،<br>إدارة منصة Eventy360</p>", "en": "<p>Dear Esteemed Colleague,</p><p>We are pleased to invite you to join the management team of the Eventy360 platform as an administrator. This invitation reflects our confidence in your expertise and qualifications to contribute to the development and management of the platform.</p><p>Please click on the link below to complete your administrator account registration process:</p><p><a href=\"[signin_link]\">Accept Invitation</a></p><p>Please note that this link is valid for [validity_period] from the date of receiving this message.</p><p>Important Note: If you were not expecting to receive this invitation, or if you have any inquiries, please contact us directly at [platform_management_email], and do not take any action regarding this message.</p><p>We look forward to your joining our team and working together to achieve the platform''s objectives.</p><p>With sincere appreciation and respect,<br>Eventy360 Platform Management</p>", "fr": "<p>Cher(ère) Collègue Estimé(e),</p><p>Nous avons le plaisir de vous inviter à rejoindre l''équipe de gestion de la plateforme Eventy360 en tant qu''administrateur. Cette invitation reflète notre confiance en votre expertise et vos qualifications pour contribuer au développement et à la gestion de la plateforme.</p><p>Veuillez cliquer sur le lien ci-dessous pour compléter votre processus d''inscription en tant qu''administrateur :</p><p><a href=\"[signin_link]\">Accepter l''invitation</a></p><p>Veuillez noter que ce lien est valable pendant [validity_period] à compter de la date de réception de ce message.</p><p>Note importante : Si vous ne vous attendiez pas à recevoir cette invitation, ou si vous avez des questions, veuillez nous contacter directement à [platform_management_email], et ne prenez aucune mesure concernant ce message.</p><p>Nous nous réjouissons de vous accueillir dans notre équipe et de travailler ensemble pour atteindre les objectifs de la plateforme.</p><p>Avec notre sincère considération et respect,<br>La Direction de la Plateforme Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-15 12:14:46.638616+00',
        '2025-05-15 12:14:46.638616+00'
    ),
    (
        'user_verified_badge_awarded',
        '{"ar": "تهانينا على حصولكم على شارة التوثيق في منصة Eventy360", "en": "Congratulations on Your Eventy360 Verification Badge", "fr": "Félicitations pour votre badge de vérification Eventy360"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>يسرنا إعلامكم بأنه قد تم منحكم شارة التوثيق الرسمية على منصة Eventy360. تعد هذه الشارة بمثابة دليل على موثوقية حسابكم وتميزكم ضمن مجتمعنا الأكاديمي.</p><p>يمكنكم الاطلاع على ملفكم الشخصي والشارة الجديدة من خلال الرابط التالي: <a href=\"[profile_page_link]\">الملف الشخصي</a></p><p>نشكركم على انضمامكم لمجتمع Eventy360 ونتطلع إلى مساهمتكم القيمة.</p><p>مع خالص التقدير والاحترام،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We are pleased to inform you that your profile on Eventy360 has been awarded the official verification badge. This badge serves as a testament to your credibility and distinction within our academic community.</p><p>You can view your profile and new badge through the following link: <a href=\"[profile_page_link]\">Profile Page</a></p><p>Thank you for being part of the Eventy360 community. We look forward to your valuable contributions.</p><p>With sincere appreciation,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous avons le plaisir de vous informer que votre profil sur Eventy360 a reçu le badge de vérification officiel. Ce badge témoigne de votre crédibilité et de votre distinction au sein de notre communauté académique.</p><p>Vous pouvez consulter votre profil et votre nouveau badge via le lien suivant : <a href=\"[profile_page_link]\">Page de profil</a></p><p>Nous vous remercions de faire partie de la communauté Eventy360 et nous nous réjouissons de vos précieuses contributions.</p><p>Avec notre sincère considération,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-15 12:14:46.638616+00',
        '2025-05-15 12:14:46.638616+00'
    ),
    (
        'payment_received_pending_verification',
        '{"ar": "استلام دفعتكم - قيد المراجعة والتحقق", "en": "Payment Received - Under Review", "fr": "Paiement reçu - En cours d''examen"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأننا استلمنا إشعار دفعتكم بنجاح. سيقوم فريقنا المختص بمراجعة تفاصيل الدفع والتحقق منها خلال فترة لا تتجاوز 48 ساعة عمل، وسيتم تحديث حالة اشتراككم فور الانتهاء من عملية التحقق.</p><p>تفاصيل العملية:<br>- رقم المرجع: [رقم المرجع]<br>- المبلغ: [المبلغ]<br>- التاريخ: [التاريخ]</p><p>في حال وجود أي استفسارات تتعلق بعملية الدفع، يرجى التواصل مع قسم المالية على [بريد قسم المالية].</p><p>نشكركم على ثقتكم بخدماتنا.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We are pleased to inform you that we have successfully received your payment notification. Our specialized team will review and verify the payment details within a period not exceeding 48 business hours, and your subscription status will be updated immediately upon completion of the verification process.</p><p>Transaction Details:<br>- Reference Number: [Reference Number]<br>- Amount: [Amount]<br>- Date: [Date]</p><p>Should you have any inquiries regarding the payment process, please contact our finance department at [Finance Department Email].</p><p>Thank you for your trust in our services.</p><p>With sincere appreciation,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous avons le plaisir de vous informer que nous avons bien reçu votre notification de paiement. Notre équipe spécialisée examinera et vérifiera les détails du paiement dans un délai ne dépassant pas 48 heures ouvrables, et l''état de votre abonnement sera mis à jour immédiatement après la finalisation du processus de vérification.</p><p>Détails de la transaction :<br>- Numéro de référence : [Numéro de référence]<br>- Montant : [Montant]<br>- Date : [Date]</p><p>Si vous avez des questions concernant le processus de paiement, veuillez contacter notre département financier à [Email du département financier].</p><p>Nous vous remercions de votre confiance en nos services.</p><p>Avec notre sincère considération,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-15 12:14:46.638616+00',
        '2025-05-15 12:14:46.638616+00'
    ),
    (
        'subscription_activated',
        '{"ar": "تم تفعيل اشتراككم بنجاح في منصة Eventy360", "en": "Your Eventy360 Subscription Has Been Successfully Activated", "fr": "Votre abonnement Eventy360 a été activé avec succès"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>يسرنا إعلامكم بأنه قد تم تفعيل اشتراككم في منصة Eventy360 بنجاح. بإمكانكم الآن الاستفادة من كافة المزايا والخدمات المتاحة ضمن باقة اشتراككم.</p><p>تفاصيل الاشتراك:<br>- نوع الباقة: [نوع الباقة]<br>- تاريخ البدء: [تاريخ البدء]<br>- تاريخ الانتهاء: [تاريخ الانتهاء]</p><p>يمكنكم إدارة اشتراككم والاطلاع على التفاصيل من خلال الرابط التالي: [رابط صفحة إدارة الاشتراك]</p><p>نشكركم على ثقتكم بمنصة Eventy360، ونتطلع إلى تقديم تجربة أكاديمية متميزة لكم.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We are pleased to inform you that your subscription to the Eventy360 platform has been successfully activated. You can now take advantage of all the features and services available within your subscription package.</p><p>Subscription Details:<br>- Package Type: [Package Type]<br>- Start Date: [Start Date]<br>- End Date: [End Date]</p><p>You can manage your subscription and view the details through the following link: [Subscription Management Page Link]</p><p>Thank you for your trust in the Eventy360 platform. We look forward to providing you with an exceptional academic experience.</p><p>With sincere appreciation,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous avons le plaisir de vous informer que votre abonnement à la plateforme Eventy360 a été activé avec succès. Vous pouvez désormais profiter de toutes les fonctionnalités et services disponibles dans votre forfait d''abonnement.</p><p>Détails de l''abonnement :<br>- Type de forfait : [Type de forfait]<br>- Date de début : [Date de début]<br>- Date de fin : [Date de fin]</p><p>Vous pouvez gérer votre abonnement et consulter les détails via le lien suivant : [Lien de la page de gestion d''abonnement]</p><p>Nous vous remercions de votre confiance en la plateforme Eventy360 et nous nous réjouissons de vous offrir une expérience académique exceptionnelle.</p><p>Avec notre sincère considération,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-15 12:14:46.638616+00',
        '2025-05-15 12:14:46.638616+00'
    ),
    (
        'trial_ending_soon',
        '{"ar": "تنبيه: اقتراب انتهاء فترة التجربة المجانية", "en": "Alert: Your Free Trial Period Is Ending Soon", "fr": "Alerte : Votre période d''essai gratuit se termine bientôt"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأن فترة التجربة المجانية لاشتراككم في منصة Eventy360 ستنتهي قريباً في تاريخ [تاريخ الانتهاء].</p><p>نأمل أن تكونوا قد استفدتم من تجربة منصتنا خلال هذه الفترة. للاستمرار في الاستفادة من كافة الميزات والخدمات دون انقطاع، ندعوكم لترقية اشتراككم إلى إحدى باقاتنا المدفوعة.</p><p>يمكنكم الاطلاع على خيارات الترقية المتاحة وإتمام عملية الدفع من خلال الرابط التالي: [رابط صفحة الترقية/الدفع]</p><p>في حال وجود أي استفسارات أو مساعدة مطلوبة، يرجى التواصل مع فريق الدعم على [بريد الدعم].</p><p>نشكركم على اهتمامكم بمنصة Eventy360.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We wish to inform you that your free trial period for the Eventy360 platform will expire soon on [Expiry Date].</p><p>We hope you have benefited from experiencing our platform during this period. To continue enjoying all features and services without interruption, we invite you to upgrade your subscription to one of our paid packages.</p><p>You can view the available upgrade options and complete the payment process through the following link: [Upgrade/Payment Page Link]</p><p>Should you have any inquiries or require assistance, please contact our support team at [Support Email].</p><p>Thank you for your interest in the Eventy360 platform.</p><p>With sincere regards,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous souhaitons vous informer que votre période d''essai gratuit pour la plateforme Eventy360 expirera prochainement le [Date d''expiration].</p><p>Nous espérons que vous avez bénéficié de l''expérience de notre plateforme pendant cette période. Pour continuer à profiter de toutes les fonctionnalités et services sans interruption, nous vous invitons à mettre à niveau votre abonnement vers l''un de nos forfaits payants.</p><p>Vous pouvez consulter les options de mise à niveau disponibles et finaliser le processus de paiement via le lien suivant : [Lien de la page de mise à niveau/paiement]</p><p>Si vous avez des questions ou besoin d''assistance, veuillez contacter notre équipe de support à [Email de support].</p><p>Nous vous remercions de votre intérêt pour la plateforme Eventy360.</p><p>Cordialement,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-15 12:14:46.638616+00',
        '2025-05-15 12:14:46.638616+00'
    ),
    (
        'trial_expired',
        '{"ar": "انتهاء فترة التجربة المجانية لاشتراككم", "en": "Your Free Trial Period Has Expired", "fr": "Votre période d''essai gratuit a expiré"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأن فترة التجربة المجانية لاشتراككم في منصة Eventy360 قد انتهت. لاستعادة الوصول الكامل إلى جميع الميزات والخدمات، ندعوكم لترقية حسابكم إلى إحدى باقاتنا المدفوعة.</p><p>بإمكانكم الاطلاع على خيارات الترقية المتاحة وإتمام عملية الدفع من خلال الرابط التالي: [رابط صفحة الترقية/الدفع]</p><p>تفاصيل الاشتراك المنتهي:<br>- نوع الباقة: تجريبية<br>- تاريخ الانتهاء: [تاريخ الانتهاء]</p><p>في حال وجود أي استفسارات أو مساعدة مطلوبة، يرجى التواصل مع فريق الدعم على [بريد الدعم].</p><p>نشكركم على اهتمامكم بمنصة Eventy360.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We wish to inform you that your free trial period for the Eventy360 platform has expired. To regain full access to all features and services, we invite you to upgrade your account to one of our paid packages.</p><p>You can view the available upgrade options and complete the payment process through the following link: [Upgrade/Payment Page Link]</p><p>Expired Subscription Details:<br>- Package Type: Trial<br>- Expiry Date: [Expiry Date]</p><p>Should you have any inquiries or require assistance, please contact our support team at [Support Email].</p><p>Thank you for your interest in the Eventy360 platform.</p><p>With sincere regards,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous souhaitons vous informer que votre période d''essai gratuit pour la plateforme Eventy360 a expiré. Pour retrouver un accès complet à toutes les fonctionnalités et services, nous vous invitons à mettre à niveau votre compte vers l''un de nos forfaits payants.</p><p>Vous pouvez consulter les options de mise à niveau disponibles et finaliser le processus de paiement via le lien suivant : [Lien de la page de mise à niveau/paiement]</p><p>Détails de l''abonnement expiré :<br>- Type de forfait : Essai<br>- Date d''expiration : [Date d''expiration]</p><p>Si vous avez des questions ou besoin d''assistance, veuillez contacter notre équipe de support à [Email de support].</p><p>Nous vous remercions de votre intérêt pour la plateforme Eventy360.</p><p>Cordialement,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-15 12:14:46.638616+00',
        '2025-05-15 12:14:46.638616+00'
    ),
    (
        'user_verified_badge_removed',
        '{"ar": "إشعار بخصوص شارة التوثيق في منصة Eventy360", "en": "Notice Regarding Your Eventy360 Verification Badge", "fr": "Avis concernant votre badge de vérification Eventy360"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأنه تمت مراجعة طلب التوثيق الخاص بكم على منصة Eventy360 ولم يتم الموافقة عليه.</p><p>السبب: [rejection_reason]</p><p>يمكنكم تقديم طلب توثيق جديد مع مستندات محدثة إذا كنتم ترغبون في المحاولة مرة أخرى.</p><p>نشكركم على تفهمكم وتعاونكم.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We wish to inform you that your verification request on the Eventy360 platform has been reviewed and was not approved.</p><p>Reason: [rejection_reason]</p><p>You may submit a new verification request with updated documents if you wish to try again.</p><p>Thank you for your understanding and cooperation.</p><p>With sincere regards,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous souhaitons vous informer que votre demande de vérification sur la plateforme Eventy360 a été examinée et n''a pas été approuvée.</p><p>Raison: [rejection_reason]</p><p>Vous pouvez soumettre une nouvelle demande de vérification avec des documents mis à jour si vous souhaitez essayer à nouveau.</p><p>Nous vous remercions de votre compréhension et de votre coopération.</p><p>Cordialement,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-15 12:14:46.638616+00',
        '2025-05-15 12:14:46.638616+00'
    ),
    (
        'verification_request_submitted',
        '{"ar": "تم استلام طلب التوثيق الخاص بكم في منصة Eventy360", "en": "Your Eventy360 Verification Request Received", "fr": "Votre demande de vérification Eventy360 reçue"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إشعاركم بأننا استلمنا طلب التوثيق الخاص بكم على منصة Eventy360 بنجاح. سيقوم فريقنا بمراجعة طلبكم في أقرب وقت ممكن.</p><p>تفاصيل الطلب:<br>- تاريخ التقديم: [submission_date]</p><p>سيتم إشعاركم عبر البريد الإلكتروني بمجرد الانتهاء من مراجعة طلبكم.</p><p>يمكنكم متابعة حالة الطلب من خلال صفحة ملفكم الشخصي.</p><p>مع خالص التقدير والاحترام،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We would like to inform you that we have successfully received your verification request on the Eventy360 platform. Our team will review your request as soon as possible.</p><p>Request Details:<br>- Submission Date: [submission_date]</p><p>You will be notified by email once your request has been reviewed.</p><p>You can check the status of your request through your profile page.</p><p>With sincere appreciation,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous souhaitons vous informer que nous avons bien reçu votre demande de vérification sur la plateforme Eventy360. Notre équipe examinera votre demande dans les plus brefs délais.</p><p>Détails de la demande:<br>- Date de soumission: [submission_date]</p><p>Vous serez notifié(e) par email dès que votre demande aura été examinée.</p><p>Vous pouvez vérifier l''état de votre demande sur votre page de profil.</p><p>Avec notre sincère considération,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-19 14:20:39.738252+00',
        '2025-05-19 14:20:39.738252+00'
    ),
    (
        'abstract_deadline_approaching',
        '{"ar": "اقتراب الموعد النهائي لتقديم الملخص العلمي لمؤتمر {{event_name.ar}}", "en": "Abstract submission deadline approaching for {{event_name.en}}", "fr": "Date limite de soumission des résumés approchant pour {{event_name.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>نود تذكيركم بأن الموعد النهائي لتقديم الملخص العلمي لمؤتمر <strong>{{event_name.ar}}</strong> يقترب. الموعد النهائي هو <strong>{{deadline}}</strong>.</p>\r\n               <p>لتقديم ملخصكم العلمي، يرجى زيارة صفحة المؤتمر والنقر على زر \"تقديم ملخص\".</p>\r\n               <p>نشكركم على اهتمامكم بهذا المؤتمر العلمي.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>This is a reminder that the abstract submission deadline for <strong>{{event_name.en}}</strong> is approaching. The deadline is <strong>{{deadline}}</strong>.</p>\r\n               <p>To submit your abstract, please visit the event page and click on the \"Submit Abstract\" button.</p>\r\n               <p>Thank you for your interest in this event.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous vous rappelons que la date limite de soumission des résumés pour <strong>{{event_name.fr}}</strong> approche. La date limite est fixée au <strong>{{deadline}}</strong>.</p>\r\n               <p>Pour soumettre votre résumé, veuillez vous rendre sur la page de l\\''événement et cliquer sur le bouton \"Soumettre un résumé\".</p>\r\n               <p>Nous vous remercions de l\\''intérêt que vous portez à cet événement.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "يتم إرسالها إلى الباحثين لتذكيرهم بالمواعيد النهائية القادمة لتقديم الملخصات العلمية", "en": "Sent to researchers to remind them of approaching abstract submission deadlines", "fr": "Envoyé aux chercheurs pour leur rappeler les dates limites de soumission des résumés à venir"}',
        '{event_name,event_id,deadline}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'full_paper_deadline_approaching',
        '{"ar": "اقتراب الموعد النهائي لتقديم البحث الكامل لمؤتمر {{event_name.ar}}", "en": "Full paper submission deadline approaching for {{event_name.en}}", "fr": "Date limite de soumission des articles complets approchant pour {{event_name.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>نود تذكيركم بأن الموعد النهائي لتقديم البحث الكامل لمؤتمر <strong>{{event_name.ar}}</strong> يقترب. الموعد النهائي هو <strong>{{deadline}}</strong>.</p>\r\n               <p>لقد تم قبول ملخصكم العلمي، ويسرنا دعوتكم لتقديم البحث الكامل. يرجى زيارة صفحة المؤتمر والنقر على زر \"تقديم البحث الكامل\".</p>\r\n               <p>نشكركم على مساهمتكم القيمة في هذا المؤتمر العلمي.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>This is a reminder that the full paper submission deadline for <strong>{{event_name.en}}</strong> is approaching. The deadline is <strong>{{deadline}}</strong>.</p>\r\n               <p>Your abstract has been accepted, and you are now invited to submit your full paper. Please visit the event page and click on the \"Submit Full Paper\" button.</p>\r\n               <p>Thank you for your contribution to this event.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous vous rappelons que la date limite de soumission des articles complets pour <strong>{{event_name.fr}}</strong> approche. La date limite est fixée au <strong>{{deadline}}</strong>.</p>\r\n               <p>Votre résumé a été accepté, et vous êtes maintenant invité(e) à soumettre votre article complet. Veuillez vous rendre sur la page de l\\''événement et cliquer sur le bouton \"Soumettre un article complet\".</p>\r\n               <p>Nous vous remercions de votre contribution à cet événement.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "يتم إرسالها إلى الباحثين الذين تم قبول ملخصاتهم العلمية لتذكيرهم بالمواعيد النهائية القادمة لتقديم الأبحاث الكاملة", "en": "Sent to researchers with accepted abstracts to remind them of approaching full paper submission deadlines", "fr": "Envoyé aux chercheurs dont les résumés ont été acceptés pour leur rappeler les dates limites de soumission des articles complets à venir"}',
        '{event_name,event_id,submission_id,deadline}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'abstract_received_confirmation',
        '{"ar": "تم استلام الملخص العلمي: {{submission_title.ar}}", "en": "Abstract Received: {{submission_title.en}}", "fr": "Résumé reçu: {{submission_title.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>يسرنا أن نؤكد استلامنا للملخص العلمي الذي قدمتموه بعنوان <strong>\"{{submission_title.ar}}\"</strong> للمؤتمر العلمي <strong>{{event_name.ar}}</strong>.</p>\r\n               <p>ملخصكم العلمي قيد التقييم حالياً. سنقوم بإخطاركم بنتيجة التقييم في أقرب وقت ممكن.</p>\r\n               <p>نشكركم على مشاركتكم العلمية القيمة.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>We are pleased to confirm that we have received your abstract submission titled <strong>\"{{submission_title.en}}\"</strong> for the event <strong>{{event_name.en}}</strong>.</p>\r\n               <p>Your abstract is now under review. We will notify you of the review outcome as soon as possible.</p>\r\n               <p>Thank you for your submission.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous avons le plaisir de vous confirmer que nous avons bien reçu votre résumé intitulé <strong>\"{{submission_title.fr}}\"</strong> pour l\\''événement <strong>{{event_name.fr}}</strong>.</p>\r\n               <p>Votre résumé est maintenant en cours d\\''évaluation. Nous vous informerons du résultat de l\\''évaluation dès que possible.</p>\r\n               <p>Nous vous remercions pour votre soumission.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "تأكيد يرسل إلى الباحثين عند استلام ملخصاتهم العلمية", "en": "Confirmation sent to researchers when their abstract submission is received", "fr": "Confirmation envoyée aux chercheurs lorsque leur résumé est reçu"}',
        '{event_name,event_id,submission_id,submission_title}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'abstract_accepted_notification',
        '{"ar": "تم قبول الملخص العلمي: {{submission_title.ar}}", "en": "Abstract Accepted: {{submission_title.en}}", "fr": "Résumé accepté: {{submission_title.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>يسرنا إبلاغكم بأن ملخصكم العلمي بعنوان <strong>\"{{submission_title.ar}}\"</strong> للمؤتمر العلمي <strong>{{event_name.ar}}</strong> قد تم قبوله.</p>\r\n               <p>ندعوكم الآن لتقديم بحثكم الكامل. يرجى زيارة صفحة المؤتمر للحصول على مزيد من المعلومات حول عملية تقديم البحث الكامل والموعد النهائي.</p>\r\n               <p>تهانينا، ونشكركم على مساهمتكم العلمية القيمة.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>We are pleased to inform you that your abstract titled <strong>\"{{submission_title.en}}\"</strong> for the event <strong>{{event_name.en}}</strong> has been accepted.</p>\r\n               <p>You are now invited to submit your full paper. Please visit the event page for more information on the full paper submission process and deadline.</p>\r\n               <p>Congratulations, and thank you for your valuable contribution.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous avons le plaisir de vous informer que votre résumé intitulé <strong>\"{{submission_title.fr}}\"</strong> pour l\\''événement <strong>{{event_name.fr}}</strong> a été accepté.</p>\r\n               <p>Vous êtes maintenant invité(e) à soumettre votre article complet. Veuillez consulter la page de l\\''événement pour plus d\\''informations sur le processus de soumission et la date limite.</p>\r\n               <p>Félicitations, et merci pour votre précieuse contribution.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "إشعار يرسل إلى الباحثين عند قبول ملخصاتهم العلمية", "en": "Notification sent to researchers when their abstract has been accepted", "fr": "Notification envoyée aux chercheurs lorsque leur résumé a été accepté"}',
        '{event_name,event_id,submission_id,submission_title,feedback}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'abstract_rejected_notification',
        '{"ar": "نتيجة تقييم الملخص العلمي: {{submission_title.ar}}", "en": "Abstract Review Result: {{submission_title.en}}", "fr": "Résultat de l\\''évaluation du résumé: {{submission_title.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>نشكركم على تقديم ملخصكم العلمي بعنوان <strong>\"{{submission_title.ar}}\"</strong> للمؤتمر العلمي <strong>{{event_name.ar}}</strong>.</p>\r\n               <p>بعد التقييم العلمي الدقيق، نأسف لإبلاغكم بأن ملخصكم العلمي لم يتم قبوله لهذا المؤتمر.</p>\r\n               <p>{{#feedback}}<p><strong>ملاحظات المقيّمين:</strong></p><p>{{feedback.ar}}</p>{{/feedback}}</p>\r\n               <p>نقدر اهتمامكم بمؤتمرنا العلمي ونشجعكم على المشاركة في المؤتمرات العلمية المستقبلية.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>Thank you for submitting your abstract titled <strong>\"{{submission_title.en}}\"</strong> for the event <strong>{{event_name.en}}</strong>.</p>\r\n               <p>After careful review, we regret to inform you that your abstract has not been accepted for this event.</p>\r\n               <p>{{#feedback}}<p><strong>Reviewer Feedback:</strong></p><p>{{feedback.en}}</p>{{/feedback}}</p>\r\n               <p>We appreciate your interest in our event and encourage you to consider submitting to future events.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous vous remercions d\\''avoir soumis votre résumé intitulé <strong>\"{{submission_title.fr}}\"</strong> pour l\\''événement <strong>{{event_name.fr}}</strong>.</p>\r\n               <p>Après un examen attentif, nous regrettons de vous informer que votre résumé n\\''a pas été retenu pour cet événement.</p>\r\n               <p>{{#feedback}}<p><strong>Commentaires des évaluateurs:</strong></p><p>{{feedback.fr}}</p>{{/feedback}}</p>\r\n               <p>Nous apprécions votre intérêt pour notre événement et vous encourageons à soumettre vos travaux lors de futurs événements.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "إشعار يرسل إلى الباحثين عند رفض ملخصاتهم العلمية", "en": "Notification sent to researchers when their abstract has been rejected", "fr": "Notification envoyée aux chercheurs lorsque leur résumé a été refusé"}',
        '{event_name,event_id,submission_id,submission_title,feedback}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'full_paper_received_confirmation',
        '{"ar": "تم استلام البحث الكامل: {{submission_title.ar}}", "en": "Full Paper Received: {{submission_title.en}}", "fr": "Article complet reçu: {{submission_title.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>يسرنا أن نؤكد استلامنا للبحث الكامل الذي قدمتموه بعنوان <strong>\"{{submission_title.ar}}\"</strong> للمؤتمر العلمي <strong>{{event_name.ar}}</strong>.</p>\r\n               <p>بحثكم العلمي قيد التقييم حالياً. سنقوم بإخطاركم بنتيجة التقييم في أقرب وقت ممكن.</p>\r\n               <p>نشكركم على مساهمتكم العلمية القيمة.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>We are pleased to confirm that we have received your full paper submission titled <strong>\"{{submission_title.en}}\"</strong> for the event <strong>{{event_name.en}}</strong>.</p>\r\n               <p>Your paper is now under review. We will notify you of the review outcome as soon as possible.</p>\r\n               <p>Thank you for your contribution.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous avons le plaisir de vous confirmer que nous avons bien reçu votre article complet intitulé <strong>\"{{submission_title.fr}}\"</strong> pour l\\''événement <strong>{{event_name.fr}}</strong>.</p>\r\n               <p>Votre article est maintenant en cours d\\''évaluation. Nous vous informerons du résultat de l\\''évaluation dès que possible.</p>\r\n               <p>Nous vous remercions pour votre contribution.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "تأكيد يرسل إلى الباحثين عند استلام أبحاثهم الكاملة", "en": "Confirmation sent to researchers when their full paper submission is received", "fr": "Confirmation envoyée aux chercheurs lorsque leur article complet est reçu"}',
        '{event_name,event_id,submission_id,submission_title}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'full_paper_accepted_notification',
        '{"ar": "تم قبول البحث الكامل: {{submission_title.ar}}", "en": "Full Paper Accepted: {{submission_title.en}}", "fr": "Article complet accepté: {{submission_title.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>يسرنا إبلاغكم بأن بحثكم الكامل بعنوان <strong>\"{{submission_title.ar}}\"</strong> للمؤتمر العلمي <strong>{{event_name.ar}}</strong> قد تم قبوله.</p>\r\n               <p>تهانينا على هذا الإنجاز العلمي! سيتم إدراج بحثكم ضمن وقائع المؤتمر.</p>\r\n               <p>{{#feedback}}<p><strong>ملاحظات المقيّمين:</strong></p><p>{{feedback.ar}}</p>{{/feedback}}</p>\r\n               <p>نشكركم على مساهمتكم العلمية القيمة في مؤتمرنا.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>We are pleased to inform you that your full paper titled <strong>\"{{submission_title.en}}\"</strong> for the event <strong>{{event_name.en}}</strong> has been accepted.</p>\r\n               <p>Congratulations on this achievement! Your paper will be included in the event proceedings.</p>\r\n               <p>{{#feedback}}<p><strong>Reviewer Feedback:</strong></p><p>{{feedback.en}}</p>{{/feedback}}</p>\r\n               <p>Thank you for your valuable contribution to our event.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous avons le plaisir de vous informer que votre article complet intitulé <strong>\"{{submission_title.fr}}\"</strong> pour l\\''événement <strong>{{event_name.fr}}</strong> a été accepté.</p>\r\n               <p>Félicitations pour cette réussite! Votre article sera inclus dans les actes de l\\''événement.</p>\r\n               <p>{{#feedback}}<p><strong>Commentaires des évaluateurs:</strong></p><p>{{feedback.fr}}</p>{{/feedback}}</p>\r\n               <p>Nous vous remercions pour votre précieuse contribution à notre événement.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "إشعار يرسل إلى الباحثين عند قبول أبحاثهم الكاملة", "en": "Notification sent to researchers when their full paper has been accepted", "fr": "Notification envoyée aux chercheurs lorsque leur article complet a été accepté"}',
        '{event_name,event_id,submission_id,submission_title,feedback}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'full_paper_rejected_notification',
        '{"ar": "نتيجة تقييم البحث الكامل: {{submission_title.ar}}", "en": "Full Paper Review Result: {{submission_title.en}}", "fr": "Résultat de l\\''évaluation de l\\''article complet: {{submission_title.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>نشكركم على تقديم بحثكم الكامل بعنوان <strong>\"{{submission_title.ar}}\"</strong> للمؤتمر العلمي <strong>{{event_name.ar}}</strong>.</p>\r\n               <p>بعد التقييم العلمي الدقيق، نأسف لإبلاغكم بأن بحثكم الكامل لم يتم قبوله لهذا المؤتمر.</p>\r\n               <p>{{#feedback}}<p><strong>ملاحظات المقيّمين:</strong></p><p>{{feedback.ar}}</p>{{/feedback}}</p>\r\n               <p>نقدر اهتمامكم بمؤتمرنا العلمي ونشجعكم على المشاركة في المؤتمرات العلمية المستقبلية.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>Thank you for submitting your full paper titled <strong>\"{{submission_title.en}}\"</strong> for the event <strong>{{event_name.en}}</strong>.</p>\r\n               <p>After careful review, we regret to inform you that your full paper has not been accepted for this event.</p>\r\n               <p>{{#feedback}}<p><strong>Reviewer Feedback:</strong></p><p>{{feedback.en}}</p>{{/feedback}}</p>\r\n               <p>We appreciate your interest in our event and encourage you to consider submitting to future events.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous vous remercions d\\''avoir soumis votre article complet intitulé <strong>\"{{submission_title.fr}}\"</strong> pour l\\''événement <strong>{{event_name.fr}}</strong>.</p>\r\n               <p>Après un examen attentif, nous regrettons de vous informer que votre article n\\''a pas été retenu pour cet événement.</p>\r\n               <p>{{#feedback}}<p><strong>Commentaires des évaluateurs:</strong></p><p>{{feedback.fr}}</p>{{/feedback}}</p>\r\n               <p>Nous apprécions votre intérêt pour notre événement et vous encourageons à soumettre vos travaux lors de futurs événements.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "إشعار يرسل إلى الباحثين عند رفض أبحاثهم الكاملة", "en": "Notification sent to researchers when their full paper has been rejected", "fr": "Notification envoyée aux chercheurs lorsque leur article complet a été refusé"}',
        '{event_name,event_id,submission_id,submission_title,feedback}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'revision_requested_notification',
        '{"ar": "طلب تعديلات على البحث: {{submission_title.ar}}", "en": "Revision Requested: {{submission_title.en}}", "fr": "Révision demandée: {{submission_title.fr}}"}',
        '{"ar": "<p>حضرة الباحث/ة المحترم/ة،</p>\r\n               <p>نشكركم على تقديم بحثكم بعنوان <strong>\"{{submission_title.ar}}\"</strong> للمؤتمر العلمي <strong>{{event_name.ar}}</strong>.</p>\r\n               <p>بعد تقييم بحثكم، نطلب منكم إجراء بعض التعديلات على البحث قبل قبوله نهائياً.</p>\r\n               <p><strong>ملاحظات المقيّمين:</strong></p>\r\n               <p>{{feedback.ar}}</p>\r\n               <p>يرجى إجراء التعديلات المطلوبة وإعادة تقديم البحث من خلال صفحة المؤتمر في أقرب وقت ممكن.</p>\r\n               <p>نشكركم على تفهمكم وتعاونكم.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Researcher,</p>\r\n               <p>Thank you for submitting your paper titled <strong>\"{{submission_title.en}}\"</strong> for the event <strong>{{event_name.en}}</strong>.</p>\r\n               <p>After reviewing your submission, we are requesting revisions to your paper before it can be accepted.</p>\r\n               <p><strong>Reviewer Feedback:</strong></p>\r\n               <p>{{feedback.en}}</p>\r\n               <p>Please make the requested revisions and resubmit your paper through the event page as soon as possible.</p>\r\n               <p>Thank you for your understanding and cooperation.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher(e) Chercheur(euse),</p>\r\n               <p>Nous vous remercions d\\''avoir soumis votre article intitulé <strong>\"{{submission_title.fr}}\"</strong> pour l\\''événement <strong>{{event_name.fr}}</strong>.</p>\r\n               <p>Après évaluation de votre soumission, nous vous demandons d\\''apporter des révisions à votre article avant qu\\''il puisse être accepté.</p>\r\n               <p><strong>Commentaires des évaluateurs:</strong></p>\r\n               <p>{{feedback.fr}}</p>\r\n               <p>Veuillez effectuer les révisions demandées et soumettre à nouveau votre article via la page de l\\''événement dès que possible.</p>\r\n               <p>Nous vous remercions pour votre compréhension et votre coopération.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "إشعار يرسل إلى الباحثين عند طلب تعديلات على أبحاثهم", "en": "Notification sent to researchers when revisions are requested for their paper", "fr": "Notification envoyée aux chercheurs lorsque des révisions sont demandées pour leur article"}',
        '{event_name,event_id,submission_id,submission_title,feedback}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'new_abstract_submission',
        '{"ar": "تقديم ملخص علمي جديد: {{submission_title.ar}}", "en": "New Abstract Submission: {{submission_title.en}}", "fr": "Nouvelle soumission de résumé: {{submission_title.fr}}"}',
        '{"ar": "<p>عزيزي منظم المؤتمر،</p>\r\n               <p>تم تقديم ملخص علمي جديد لمؤتمركم <strong>{{event_name.ar}}</strong>.</p>\r\n               <p><strong>عنوان البحث:</strong> {{submission_title.ar}}</p>\r\n               <p><strong>الباحث:</strong> {{researcher_name}}</p>\r\n               <p>يرجى تسجيل الدخول إلى حسابكم لمراجعة هذا الملخص العلمي.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Organizer,</p>\r\n               <p>A new abstract has been submitted for your event <strong>{{event_name.en}}</strong>.</p>\r\n               <p><strong>Submission Title:</strong> {{submission_title.en}}</p>\r\n               <p><strong>Researcher:</strong> {{researcher_name}}</p>\r\n               <p>Please log in to your account to review this submission.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher Organisateur,</p>\r\n               <p>Un nouveau résumé a été soumis pour votre événement <strong>{{event_name.fr}}</strong>.</p>\r\n               <p><strong>Titre de la soumission:</strong> {{submission_title.fr}}</p>\r\n               <p><strong>Chercheur:</strong> {{researcher_name}}</p>\r\n               <p>Veuillez vous connecter à votre compte pour examiner cette soumission.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "إشعار يرسل إلى منظمي المؤتمرات العلمية عند تقديم ملخص علمي جديد", "en": "Notification sent to event organizers when a new abstract is submitted", "fr": "Notification envoyée aux organisateurs d\\''événements lorsqu\\''un nouveau résumé est soumis"}',
        '{event_name,event_id,submission_id,submission_title,researcher_name}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'new_full_paper_submission',
        '{"ar": "تقديم بحث كامل جديد: {{submission_title.ar}}", "en": "New Full Paper Submission: {{submission_title.en}}", "fr": "Nouvelle soumission d\\''article complet: {{submission_title.fr}}"}',
        '{"ar": "<p>عزيزي منظم المؤتمر،</p>\r\n               <p>تم تقديم بحث كامل جديد لمؤتمركم <strong>{{event_name.ar}}</strong>.</p>\r\n               <p><strong>عنوان البحث:</strong> {{submission_title.ar}}</p>\r\n               <p><strong>الباحث:</strong> {{researcher_name}}</p>\r\n               <p>يرجى تسجيل الدخول إلى حسابكم لمراجعة هذا البحث العلمي.</p>\r\n               <p>مع فائق الاحترام والتقدير،<br>فريق منصة Eventy360</p>", "en": "<p>Dear Organizer,</p>\r\n               <p>A new full paper has been submitted for your event <strong>{{event_name.en}}</strong>.</p>\r\n               <p><strong>Submission Title:</strong> {{submission_title.en}}</p>\r\n               <p><strong>Researcher:</strong> {{researcher_name}}</p>\r\n               <p>Please log in to your account to review this submission.</p>\r\n               <p>Best regards,<br>Eventy360 Team</p>", "fr": "<p>Cher Organisateur,</p>\r\n               <p>Un nouvel article complet a été soumis pour votre événement <strong>{{event_name.fr}}</strong>.</p>\r\n               <p><strong>Titre de la soumission:</strong> {{submission_title.fr}}</p>\r\n               <p><strong>Chercheur:</strong> {{researcher_name}}</p>\r\n               <p>Veuillez vous connecter à votre compte pour examiner cette soumission.</p>\r\n               <p>Cordialement,<br>L\\''équipe Eventy360</p>"}',
        '{"ar": "إشعار يرسل إلى منظمي المؤتمرات العلمية عند تقديم بحث كامل جديد", "en": "Notification sent to event organizers when a new full paper is submitted", "fr": "Notification envoyée aux organisateurs d\\''événements lorsqu\\''un nouvel article complet est soumis"}',
        '{event_name,event_id,submission_id,submission_title,researcher_name}',
        '2025-05-25 13:38:20.234555+00',
        '2025-05-25 13:38:20.234555+00'
    ),
    (
        'payment_verified_notification',
        '{"ar": "تم التحقق من دفعتكم وتفعيل الاشتراك", "en": "Payment Verified and Subscription Activated", "fr": "Paiement vérifié et abonnement activé"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>يسرنا إعلامكم بأنه تم التحقق من دفعتكم بنجاح وتفعيل اشتراككم في منصة Eventy360. يمكنكم الآن الاستفادة من جميع الميزات المتاحة ضمن باقة اشتراككم.</p><p>تفاصيل الدفع:<br>- رقم المرجع: [reference_number]<br>- المبلغ: [amount] د.ج<br>- طريقة الدفع: [payment_method]<br>- فترة الاشتراك: [billing_period]</p><p>تفاصيل الاشتراك:<br>- نوع الباقة: [subscription_tier]<br>- تاريخ البدء: [start_date]<br>- تاريخ الانتهاء: [end_date]</p><p>يمكنكم إدارة اشتراككم والاطلاع على التفاصيل من خلال صفحة إدارة الاشتراك على المنصة.</p><p>نشكركم على ثقتكم بمنصة Eventy360، ونتطلع إلى تقديم تجربة أكاديمية متميزة لكم.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We are pleased to inform you that your payment has been successfully verified and your subscription to the Eventy360 platform has been activated. You can now take advantage of all the features available within your subscription package.</p><p>Payment Details:<br>- Reference Number: [reference_number]<br>- Amount: [amount] DZD<br>- Payment Method: [payment_method]<br>- Billing Period: [billing_period]</p><p>Subscription Details:<br>- Package Type: [subscription_tier]<br>- Start Date: [start_date]<br>- End Date: [end_date]</p><p>You can manage your subscription and view the details through your account dashboard on the platform.</p><p>Thank you for your trust in the Eventy360 platform. We look forward to providing you with an exceptional academic experience.</p><p>With sincere appreciation,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous avons le plaisir de vous informer que votre paiement a été vérifié avec succès et que votre abonnement à la plateforme Eventy360 a été activé. Vous pouvez désormais profiter de toutes les fonctionnalités disponibles dans votre forfait d''abonnement.</p><p>Détails du paiement :<br>- Numéro de référence : [reference_number]<br>- Montant : [amount] DZD<br>- Méthode de paiement : [payment_method]<br>- Période de facturation : [billing_period]</p><p>Détails de l''abonnement :<br>- Type de forfait : [subscription_tier]<br>- Date de début : [start_date]<br>- Date de fin : [end_date]</p><p>Vous pouvez gérer votre abonnement et consulter les détails via votre tableau de bord sur la plateforme.</p><p>Nous vous remercions de votre confiance en la plateforme Eventy360 et nous nous réjouissons de vous offrir une expérience académique exceptionnelle.</p><p>Avec notre sincère considération,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-31 19:37:52.975576+00',
        '2025-05-31 19:37:52.975576+00'
    ),
    (
        'payment_rejected_notification',
        '{"ar": "إشعار بخصوص دفعتكم - المراجعة لم تكتمل", "en": "Notice Regarding Your Payment - Verification Not Completed", "fr": "Avis concernant votre paiement - Vérification non complétée"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأننا قمنا بمراجعة دفعتكم المقدمة، ونأسف لإبلاغكم بأن عملية التحقق لم تكتمل بنجاح للأسباب التالية:</p><p>[rejection_reason]</p><p>تفاصيل الدفع المرفوض:<br>- رقم المرجع: [reference_number]<br>- المبلغ: [amount] د.ج<br>- تاريخ التقديم: [reported_date]</p><p>يمكنكم إعادة تقديم طلب الدفع مع مراعاة الأسباب المذكورة أعلاه. للمساعدة، يرجى التواصل مع فريق الدعم على [support_email].</p><p>نشكركم على تفهمكم وتعاونكم.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>", "en": "<p>Dear Esteemed Member,</p><p>We wish to inform you that we have reviewed your submitted payment, and regret to inform you that the verification process could not be completed successfully for the following reasons:</p><p>[rejection_reason]</p><p>Rejected Payment Details:<br>- Reference Number: [reference_number]<br>- Amount: [amount] DZD<br>- Submission Date: [reported_date]</p><p>You may resubmit a payment request, considering the reasons mentioned above. For assistance, please contact our support team at [support_email].</p><p>Thank you for your understanding and cooperation.</p><p>With sincere regards,<br>The Eventy360 Team</p>", "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous souhaitons vous informer que nous avons examiné votre paiement soumis, et regrettons de vous informer que le processus de vérification n''a pas pu être complété avec succès pour les raisons suivantes :</p><p>[rejection_reason]</p><p>Détails du paiement rejeté :<br>- Numéro de référence : [reference_number]<br>- Montant : [amount] DZD<br>- Date de soumission : [reported_date]</p><p>Vous pouvez soumettre à nouveau une demande de paiement, en tenant compte des raisons mentionnées ci-dessus. Pour obtenir de l''aide, veuillez contacter notre équipe de support à [support_email].</p><p>Nous vous remercions de votre compréhension et de votre coopération.</p><p>Cordialement,<br>L''Équipe Eventy360</p>"}',
        NULL,
        NULL,
        '2025-05-31 19:37:52.975576+00',
        '2025-05-31 19:37:52.975576+00'
    );