-- Create the ENUM type for admin action types
CREATE TYPE admin_action_type AS ENUM (
  'awarded_badge',
  'removed_badge',
  'recorded_payment',
  'updated_payment_status',
  'admin_login',
  'admin_user_edit',
  'admin_event_edit',
  'admin_submission_edit',
  'admin_topic_create',
  'admin_topic_update',
  'admin_topic_delete',
  'admin_email_template_edit'
);

-- Create the admin_actions_log table
CREATE TABLE admin_actions_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  admin_user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  action_type admin_action_type NOT NULL,
  target_user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  target_entity_id UUID,
  target_entity_type TEXT,
  details JSONB,
  ip_address INET
);

-- Add indexes for performance
CREATE INDEX idx_admin_actions_log_admin_user_id ON admin_actions_log(admin_user_id);
CREATE INDEX idx_admin_actions_log_target_user_id ON admin_actions_log(target_user_id);
CREATE INDEX idx_admin_actions_log_action_type ON admin_actions_log(action_type);
CREATE INDEX idx_admin_actions_log_created_at ON admin_actions_log(created_at);
CREATE INDEX idx_admin_actions_log_target_entity ON admin_actions_log(target_entity_id, target_entity_type);

-- RLS Policies for admin_actions_log
ALTER TABLE admin_actions_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin read access to all logs"
ON admin_actions_log
FOR SELECT
TO authenticated
USING (
  (SELECT profiles.user_type FROM profiles WHERE profiles.id = auth.uid()) = 'admin'
);

CREATE POLICY "Allow admin users to insert their own logs"
ON admin_actions_log
FOR INSERT
TO authenticated
WITH CHECK (
  (SELECT profiles.user_type FROM profiles WHERE profiles.id = auth.uid()) = 'admin' AND
  admin_user_id = auth.uid()
);

CREATE POLICY "Deny direct updates to logs"
ON admin_actions_log
FOR UPDATE
TO authenticated
USING (false);

CREATE POLICY "Deny direct deletes from logs"
ON admin_actions_log
FOR DELETE
TO authenticated
USING (false);

GRANT USAGE ON TYPE admin_action_type TO authenticated;

GRANT SELECT, INSERT ON TABLE admin_actions_log TO authenticated;
GRANT ALL ON TABLE admin_actions_log TO supabase_admin; 