-- First delete existing templates to ensure idempotency
DELETE FROM public.email_templates
WHERE
    template_key IN (
        'user_verified_badge_awarded',
        'user_verified_badge_removed',
        'payment_received_pending_verification',
        'subscription_activated',
        'trial_ending_soon',
        'trial_expired',
        'admin_invitation'
    );

-- Then insert the templates with proper formatting
INSERT INTO
    public.email_templates (
        template_key,
        subject_translations,
        body_html_translations
    )
VALUES
    (
        'user_verified_badge_awarded',
        '{"ar": "تهانينا على حصولكم على شارة التوثيق في منصة Eventy360", "en": "Congratulations on Your Eventy360 Verification Badge", "fr": "Félicitations pour votre badge de vérification Eventy360"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>يسرنا إعلامكم بأنه قد تم منحكم شارة التوثيق الرسمية على منصة Eventy360. تعد هذه الشارة بمثابة دليل على موثوقية حسابكم وتميزكم ضمن مجتمعنا الأكاديمي.</p><p>يمكنكم الاطلاع على ملفكم الشخصي والشارة الجديدة من خلال الرابط التالي: [رابط صفحة الملف الشخصي]</p><p>نشكركم على انضمامكم لمجتمع Eventy360 ونتطلع إلى مساهمتكم القيمة.</p><p>مع خالص التقدير والاحترام،<br>فريق Eventy360</p>", 
        "en": "<p>Dear Esteemed Member,</p><p>We are pleased to inform you that your profile on Eventy360 has been awarded the official verification badge. This badge serves as a testament to your credibility and distinction within our academic community.</p><p>You can view your profile and new badge through the following link: [Profile Page Link]</p><p>Thank you for being part of the Eventy360 community. We look forward to your valuable contributions.</p><p>With sincere appreciation,<br>The Eventy360 Team</p>",
        "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous avons le plaisir de vous informer que votre profil sur Eventy360 a reçu le badge de vérification officiel. Ce badge témoigne de votre crédibilité et de votre distinction au sein de notre communauté académique.</p><p>Vous pouvez consulter votre profil et votre nouveau badge via le lien suivant : [Lien de la page de profil]</p><p>Nous vous remercions de faire partie de la communauté Eventy360 et nous nous réjouissons de vos précieuses contributions.</p><p>Avec notre sincère considération,<br>L''Équipe Eventy360</p>"}'
    ),
    (
        'user_verified_badge_removed',
        '{"ar": "إشعار بخصوص شارة التوثيق في منصة Eventy360", "en": "Notice Regarding Your Eventy360 Verification Badge", "fr": "Avis concernant votre badge de vérification Eventy360"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأنه تم إزالة شارة التوثيق من ملفكم الشخصي على منصة Eventy360.</p><p>إذا كان لديكم أي استفسارات بخصوص هذا الإجراء، يرجى التواصل مع فريق الدعم الأكاديمي على البريد الإلكتروني [بريد الدعم].</p><p>يمكنكم الاطلاع على ملفكم الشخصي من خلال الرابط التالي: [رابط صفحة الملف الشخصي]</p><p>نشكركم على تفهمكم وتعاونكم.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>",
        "en": "<p>Dear Esteemed Member,</p><p>We wish to inform you that the verification badge has been removed from your profile on the Eventy360 platform.</p><p>If you have any inquiries regarding this action, please contact our academic support team at [Support Email].</p><p>You can view your profile through the following link: [Profile Page Link]</p><p>Thank you for your understanding and cooperation.</p><p>With sincere regards,<br>The Eventy360 Team</p>",
        "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous souhaitons vous informer que le badge de vérification a été retiré de votre profil sur la plateforme Eventy360.</p><p>Si vous avez des questions concernant cette action, veuillez contacter notre équipe de support académique à [Email de Support].</p><p>Vous pouvez consulter votre profil via le lien suivant : [Lien de la page de profil]</p><p>Nous vous remercions de votre compréhension et de votre coopération.</p><p>Cordialement,<br>L''Équipe Eventy360</p>"}'
    ),
    (
        'payment_received_pending_verification',
        '{"ar": "استلام دفعتكم - قيد المراجعة والتحقق", "en": "Payment Received - Under Review", "fr": "Paiement reçu - En cours d''examen"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأننا استلمنا إشعار دفعتكم بنجاح. سيقوم فريقنا المختص بمراجعة تفاصيل الدفع والتحقق منها خلال فترة لا تتجاوز 48 ساعة عمل، وسيتم تحديث حالة اشتراككم فور الانتهاء من عملية التحقق.</p><p>تفاصيل العملية:<br>- رقم المرجع: [رقم المرجع]<br>- المبلغ: [المبلغ]<br>- التاريخ: [التاريخ]</p><p>في حال وجود أي استفسارات تتعلق بعملية الدفع، يرجى التواصل مع قسم المالية على [بريد قسم المالية].</p><p>نشكركم على ثقتكم بخدماتنا.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>",
        "en": "<p>Dear Esteemed Member,</p><p>We are pleased to inform you that we have successfully received your payment notification. Our specialized team will review and verify the payment details within a period not exceeding 48 business hours, and your subscription status will be updated immediately upon completion of the verification process.</p><p>Transaction Details:<br>- Reference Number: [Reference Number]<br>- Amount: [Amount]<br>- Date: [Date]</p><p>Should you have any inquiries regarding the payment process, please contact our finance department at [Finance Department Email].</p><p>Thank you for your trust in our services.</p><p>With sincere appreciation,<br>The Eventy360 Team</p>",
        "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous avons le plaisir de vous informer que nous avons bien reçu votre notification de paiement. Notre équipe spécialisée examinera et vérifiera les détails du paiement dans un délai ne dépassant pas 48 heures ouvrables, et l''état de votre abonnement sera mis à jour immédiatement après la finalisation du processus de vérification.</p><p>Détails de la transaction :<br>- Numéro de référence : [Numéro de référence]<br>- Montant : [Montant]<br>- Date : [Date]</p><p>Si vous avez des questions concernant le processus de paiement, veuillez contacter notre département financier à [Email du département financier].</p><p>Nous vous remercions de votre confiance en nos services.</p><p>Avec notre sincère considération,<br>L''Équipe Eventy360</p>"}'
    ),
    (
        'subscription_activated',
        '{"ar": "تم تفعيل اشتراككم بنجاح في منصة Eventy360", "en": "Your Eventy360 Subscription Has Been Successfully Activated", "fr": "Votre abonnement Eventy360 a été activé avec succès"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>يسرنا إعلامكم بأنه قد تم تفعيل اشتراككم في منصة Eventy360 بنجاح. بإمكانكم الآن الاستفادة من كافة المزايا والخدمات المتاحة ضمن باقة اشتراككم.</p><p>تفاصيل الاشتراك:<br>- نوع الباقة: [نوع الباقة]<br>- تاريخ البدء: [تاريخ البدء]<br>- تاريخ الانتهاء: [تاريخ الانتهاء]</p><p>يمكنكم إدارة اشتراككم والاطلاع على التفاصيل من خلال الرابط التالي: [رابط صفحة إدارة الاشتراك]</p><p>نشكركم على ثقتكم بمنصة Eventy360، ونتطلع إلى تقديم تجربة أكاديمية متميزة لكم.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>",
        "en": "<p>Dear Esteemed Member,</p><p>We are pleased to inform you that your subscription to the Eventy360 platform has been successfully activated. You can now take advantage of all the features and services available within your subscription package.</p><p>Subscription Details:<br>- Package Type: [Package Type]<br>- Start Date: [Start Date]<br>- End Date: [End Date]</p><p>You can manage your subscription and view the details through the following link: [Subscription Management Page Link]</p><p>Thank you for your trust in the Eventy360 platform. We look forward to providing you with an exceptional academic experience.</p><p>With sincere appreciation,<br>The Eventy360 Team</p>",
        "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous avons le plaisir de vous informer que votre abonnement à la plateforme Eventy360 a été activé avec succès. Vous pouvez désormais profiter de toutes les fonctionnalités et services disponibles dans votre forfait d''abonnement.</p><p>Détails de l''abonnement :<br>- Type de forfait : [Type de forfait]<br>- Date de début : [Date de début]<br>- Date de fin : [Date de fin]</p><p>Vous pouvez gérer votre abonnement et consulter les détails via le lien suivant : [Lien de la page de gestion d''abonnement]</p><p>Nous vous remercions de votre confiance en la plateforme Eventy360 et nous nous réjouissons de vous offrir une expérience académique exceptionnelle.</p><p>Avec notre sincère considération,<br>L''Équipe Eventy360</p>"}'
    ),
    (
        'trial_ending_soon',
        '{"ar": "تنبيه: اقتراب انتهاء فترة التجربة المجانية", "en": "Alert: Your Free Trial Period Is Ending Soon", "fr": "Alerte : Votre période d''essai gratuit se termine bientôt"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأن فترة التجربة المجانية لاشتراككم في منصة Eventy360 ستنتهي قريباً في تاريخ [تاريخ الانتهاء].</p><p>نأمل أن تكونوا قد استفدتم من تجربة منصتنا خلال هذه الفترة. للاستمرار في الاستفادة من كافة الميزات والخدمات دون انقطاع، ندعوكم لترقية اشتراككم إلى إحدى باقاتنا المدفوعة.</p><p>يمكنكم الاطلاع على خيارات الترقية المتاحة وإتمام عملية الدفع من خلال الرابط التالي: [رابط صفحة الترقية/الدفع]</p><p>في حال وجود أي استفسارات أو مساعدة مطلوبة، يرجى التواصل مع فريق الدعم على [بريد الدعم].</p><p>نشكركم على اهتمامكم بمنصة Eventy360.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>",
        "en": "<p>Dear Esteemed Member,</p><p>We wish to inform you that your free trial period for the Eventy360 platform will expire soon on [Expiry Date].</p><p>We hope you have benefited from experiencing our platform during this period. To continue enjoying all features and services without interruption, we invite you to upgrade your subscription to one of our paid packages.</p><p>You can view the available upgrade options and complete the payment process through the following link: [Upgrade/Payment Page Link]</p><p>Should you have any inquiries or require assistance, please contact our support team at [Support Email].</p><p>Thank you for your interest in the Eventy360 platform.</p><p>With sincere regards,<br>The Eventy360 Team</p>",
        "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous souhaitons vous informer que votre période d''essai gratuit pour la plateforme Eventy360 expirera prochainement le [Date d''expiration].</p><p>Nous espérons que vous avez bénéficié de l''expérience de notre plateforme pendant cette période. Pour continuer à profiter de toutes les fonctionnalités et services sans interruption, nous vous invitons à mettre à niveau votre abonnement vers l''un de nos forfaits payants.</p><p>Vous pouvez consulter les options de mise à niveau disponibles et finaliser le processus de paiement via le lien suivant : [Lien de la page de mise à niveau/paiement]</p><p>Si vous avez des questions ou besoin d''assistance, veuillez contacter notre équipe de support à [Email de support].</p><p>Nous vous remercions de votre intérêt pour la plateforme Eventy360.</p><p>Cordialement,<br>L''Équipe Eventy360</p>"}'
    ),
    (
        'trial_expired',
        '{"ar": "انتهاء فترة التجربة المجانية لاشتراككم", "en": "Your Free Trial Period Has Expired", "fr": "Votre période d''essai gratuit a expiré"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>نود إعلامكم بأن فترة التجربة المجانية لاشتراككم في منصة Eventy360 قد انتهت. لاستعادة الوصول الكامل إلى جميع الميزات والخدمات، ندعوكم لترقية حسابكم إلى إحدى باقاتنا المدفوعة.</p><p>بإمكانكم الاطلاع على خيارات الترقية المتاحة وإتمام عملية الدفع من خلال الرابط التالي: [رابط صفحة الترقية/الدفع]</p><p>تفاصيل الاشتراك المنتهي:<br>- نوع الباقة: تجريبية<br>- تاريخ الانتهاء: [تاريخ الانتهاء]</p><p>في حال وجود أي استفسارات أو مساعدة مطلوبة، يرجى التواصل مع فريق الدعم على [بريد الدعم].</p><p>نشكركم على اهتمامكم بمنصة Eventy360.</p><p>مع خالص التقدير،<br>فريق Eventy360</p>",
        "en": "<p>Dear Esteemed Member,</p><p>We wish to inform you that your free trial period for the Eventy360 platform has expired. To regain full access to all features and services, we invite you to upgrade your account to one of our paid packages.</p><p>You can view the available upgrade options and complete the payment process through the following link: [Upgrade/Payment Page Link]</p><p>Expired Subscription Details:<br>- Package Type: Trial<br>- Expiry Date: [Expiry Date]</p><p>Should you have any inquiries or require assistance, please contact our support team at [Support Email].</p><p>Thank you for your interest in the Eventy360 platform.</p><p>With sincere regards,<br>The Eventy360 Team</p>",
        "fr": "<p>Cher(e) Membre Estimé(e),</p><p>Nous souhaitons vous informer que votre période d''essai gratuit pour la plateforme Eventy360 a expiré. Pour retrouver un accès complet à toutes les fonctionnalités et services, nous vous invitons à mettre à niveau votre compte vers l''un de nos forfaits payants.</p><p>Vous pouvez consulter les options de mise à niveau disponibles et finaliser le processus de paiement via le lien suivant : [Lien de la page de mise à niveau/paiement]</p><p>Détails de l''abonnement expiré :<br>- Type de forfait : Essai<br>- Date d''expiration : [Date d''expiration]</p><p>Si vous avez des questions ou besoin d''assistance, veuillez contacter notre équipe de support à [Email de support].</p><p>Nous vous remercions de votre intérêt pour la plateforme Eventy360.</p><p>Cordialement,<br>L''Équipe Eventy360</p>"}'
    ),
    (
        'admin_invitation',
        '{"ar": "دعوة للانضمام كمسؤول في منصة Eventy360", "en": "Invitation to Join as an Administrator on Eventy360", "fr": "Invitation à rejoindre en tant qu''administrateur sur Eventy360"}',
        '{"ar": "<p>السيد(ة) المحترم(ة)،</p><p>يسرنا دعوتكم للانضمام إلى فريق إدارة منصة Eventy360 بصفة مسؤول. هذه الدعوة تعكس ثقتنا في خبراتكم ومؤهلاتكم للمساهمة في تطوير وإدارة المنصة.</p><p>يرجى النقر على الرابط أدناه لإكمال عملية تسجيل حسابكم كمسؤول:</p><p>[رابط دعوة المسؤول]</p><p>يرجى العلم بأن هذا الرابط صالح لمدة [مدة الصلاحية] من تاريخ استلام هذه الرسالة.</p><p>ملاحظة هامة: إذا لم تكونوا تتوقعون استلام هذه الدعوة، أو إذا كان هناك أي استفسارات، يرجى التواصل معنا مباشرة على [بريد إدارة المنصة]، وعدم اتخاذ أي إجراء بخصوص هذه الرسالة.</p><p>نتطلع إلى انضمامكم إلى فريقنا والعمل سوياً لتحقيق أهداف المنصة.</p><p>مع خالص التقدير والاحترام،<br>إدارة منصة Eventy360</p>",
        "en": "<p>Dear Esteemed Colleague,</p><p>We are pleased to invite you to join the management team of the Eventy360 platform as an administrator. This invitation reflects our confidence in your expertise and qualifications to contribute to the development and management of the platform.</p><p>Please click on the link below to complete your administrator account registration process:</p><p>[Admin Invitation Link]</p><p>Please note that this link is valid for [Validity Period] from the date of receiving this message.</p><p>Important Note: If you were not expecting to receive this invitation, or if you have any inquiries, please contact us directly at [Platform Management Email], and do not take any action regarding this message.</p><p>We look forward to your joining our team and working together to achieve the platform''s objectives.</p><p>With sincere appreciation and respect,<br>Eventy360 Platform Management</p>",
        "fr": "<p>Cher(ère) Collègue Estimé(e),</p><p>Nous avons le plaisir de vous inviter à rejoindre l''équipe de gestion de la plateforme Eventy360 en tant qu''administrateur. Cette invitation reflète notre confiance en votre expertise et vos qualifications pour contribuer au développement et à la gestion de la plateforme.</p><p>Veuillez cliquer sur le lien ci-dessous pour compléter votre processus d''inscription en tant qu''administrateur :</p><p>[Lien d''invitation administrateur]</p><p>Veuillez noter que ce lien est valable pendant [Période de validité] à compter de la date de réception de ce message.</p><p>Note importante : Si vous ne vous attendiez pas à recevoir cette invitation, ou si vous avez des questions, veuillez nous contacter directement à [Email de gestion de la plateforme], et ne prenez aucune mesure concernant ce message.</p><p>Nous nous réjouissons de vous accueillir dans notre équipe et de travailler ensemble pour atteindre les objectifs de la plateforme.</p><p>Avec notre sincère considération et respect,<br>La Direction de la Plateforme Eventy360</p>"}'
    );